version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./datavolume:/var/lib/postgresql
    networks:
      - portainer_default
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
     - portainer_default
    depends_on:
      - db

networks:
  portainer_default:
    external:
      portainer_default
